CREATE TABLE IF NOT EXISTS t_student_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    lab_id BIGINT NULL,
    student_no VARCHAR(64) NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    gender VARCHAR(16) NULL,
    college_id BIGINT NULL,
    major VARCHAR(128) NULL,
    class_name VARCHAR(128) NULL,
    phone VARCHAR(32) NULL,
    email VARCHAR(128) NULL,
    direction VARCHAR(128) NULL,
    introduction TEXT NULL,
    attachment_url VARCHAR(1024) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    current_version INT NOT NULL DEFAULT 0,
    submitted_at DATETIME NULL,
    last_review_time DATETIME NULL,
    created_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_student_profile_user (user_id),
    KEY idx_student_profile_lab (lab_id, status, create_time),
    KEY idx_student_profile_college (college_id, status, create_time),
    KEY idx_student_profile_student_no (student_no),
    KEY idx_student_profile_status (status)
);

CREATE TABLE IF NOT EXISTS t_student_profile_review (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    profile_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    reviewer_id BIGINT NULL,
    review_status VARCHAR(32) NOT NULL,
    review_comment VARCHAR(500) NULL,
    review_snapshot LONGTEXT NOT NULL,
    review_time DATETIME NULL,
    created_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_student_profile_review_version (profile_id, version_no),
    KEY idx_student_profile_review_status (review_status, create_time),
    KEY idx_student_profile_review_profile (profile_id, create_time)
);

CREATE TABLE IF NOT EXISTS t_student_profile_archive (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    profile_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    archive_snapshot LONGTEXT NOT NULL,
    archived_by BIGINT NULL,
    archived_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_student_profile_archive_version (profile_id, version_no),
    KEY idx_student_profile_archive_profile (profile_id, archived_at)
);
