INSERT IGNORE INTO t_growth_track (
    id, code, name, short_name, category, subtitle, description, fit_scene, salary_range,
    recommended_keyword, interview_position, icon_key, difficulty_label, tags_json, courses_json,
    books_json, competitions_json, certificates_json, competency_json, sort_order, status
) VALUES
    (1, 'backend', '后端开发与服务架构', 'Backend', 'engineering', '适合喜欢接口、数据模型和系统边界的同学',
     '围绕 Java、Spring Boot、数据库、缓存和服务治理展开，是当前实验室招聘里最稳定、最容易形成长期积累的方向之一。',
     '如果你做题时更关注数据结构如何落到接口、事务、缓存和服务协作上，后端路径通常会更适合你。',
     '6k-15k / 月', 'Java 基础', 'Java后端开发', 'backend', '进阶型',
     '["Java","Spring Boot","MySQL","Redis","微服务"]',
     '["黑马程序员 Java 零基础","Spring Boot 官方文档","MySQL 实战课程"]',
     '["Effective Java","高性能 MySQL","深入理解 Java 虚拟机"]',
     '["软件设计大赛","蓝桥杯软件组","企业实战项目开发赛"]',
     '["OCP Java SE","软考软件设计师","阿里云 ACA 云计算"]',
     '[{"skill":"Java 基础","target":90,"description":"集合、多线程、异常与常见设计模式需要稳定输出"},{"skill":"服务端框架","target":85,"description":"Spring Boot、事务、鉴权和接口分层要形成体系"},{"skill":"数据存储","target":82,"description":"MySQL、Redis 与 SQL 调优是后端面试高频点"}]',
     1, 1),
    (2, 'frontend', '前端工程与体验实现', 'Frontend', 'engineering', '适合喜欢可视化表达和交互细节的同学',
     '聚焦 Vue 3、TypeScript、组件设计、性能优化和工程化，强调你是否能把需求真正落成稳定易用的页面。',
     '如果你对页面细节、动效、状态管理和用户体验特别敏感，前端路径更容易做出差异化。',
     '6k-14k / 月', 'Web 逻辑', '前端开发', 'frontend', '进阶型',
     '["Vue 3","TypeScript","组件设计","性能优化","工程化"]',
     '["Vue 官方文档","TypeScript 进阶课","前端工程化训练营"]',
     '["JavaScript 高级程序设计","CSS 揭秘","Vue.js 设计与实现"]',
     '["中国大学生计算机设计大赛 Web 组","蓝桥杯 Web 应用赛","互联网产品前端实现赛"]',
     '["W3C HTML5 认证","Google UX Design Certificate","阿里云前端工程师认证"]',
     '[{"skill":"组件化能力","target":88,"description":"复杂页面要能拆成可维护组件并管理状态"},{"skill":"视觉与交互","target":82,"description":"不仅要能实现，还要理解信息层级和交互反馈"},{"skill":"工程化思维","target":80,"description":"构建、调试、发布和性能优化决定交付质量"}]',
     2, 1),
    (3, 'ai', '人工智能与模型应用', 'AI', 'data', '适合喜欢实验、模型和智能产品的同学',
     '从数据准备、模型调用、提示词设计到智能应用封装，强调你是否能把算法能力真正落成产品功能。',
     '如果你更喜欢通过实验、指标和模型效果解决问题，AI 路径通常会比传统工程路径更适合你。',
     '7k-18k / 月', '动态规划', '算法工程师', 'ai', '高强度',
     '["机器学习","深度学习","Prompt Engineering","模型评估","数据处理"]',
     '["吴恩达机器学习课程","CS231n","AI 应用开发实战"]',
     '["深度学习","机器学习","统计学习方法"]',
     '["Kaggle 竞赛","数学建模竞赛","人工智能创新赛"]',
     '["TensorFlow Developer","CDA 数据分析师","阿里云机器学习 ACP"]',
     '[{"skill":"数据理解","target":88,"description":"要会清洗样本、识别偏差并设计验证口径"},{"skill":"模型应用","target":85,"description":"不仅会调用模型，还要能控制输入输出质量"},{"skill":"实验表达","target":82,"description":"要能解释指标变化原因和方案取舍"}]',
     3, 1),
    (4, 'embedded', '嵌入式与物联网开发', 'Embedded', 'engineering', '适合喜欢软硬结合和底层控制的同学',
     '围绕单片机、驱动、实时控制和设备通信展开，强调你对资源受限环境、硬件约束和系统调试的耐心。',
     '如果你更愿意和设备、传感器、协议、驱动打交道，而不是只做页面或业务逻辑，嵌入式路径会更合适。',
     '6k-15k / 月', '数据结构', '嵌入式工程师', 'embedded', '进阶型',
     '["C/C++","STM32","驱动开发","实时系统","设备通信"]',
     '["STM32 官方教程","正点原子实战课","嵌入式 Linux 训练营"]',
     '["C 程序设计语言","深入理解计算机系统","Linux 设备驱动开发详解"]',
     '["电子设计大赛","智能汽车竞赛","物联网创新应用赛"]',
     '["ARM Accredited Engineer","软考嵌入式系统设计师","华为 IoT 认证"]',
     '[{"skill":"底层编程","target":88,"description":"指针、内存、并发与寄存器操作要稳"},{"skill":"硬件调试","target":83,"description":"要能定位信号、外设和驱动交互问题"},{"skill":"系统约束意识","target":80,"description":"实时性、功耗和资源限制决定方案设计"}]',
     4, 1),
    (5, 'security', '网络安全与攻防实践', 'Security', 'infrastructure', '适合喜欢排查风险和漏洞分析的同学',
     '聚焦 Web 安全、系统安全、权限设计、攻防演练和安全基线，强调风险识别与防护闭环能力。',
     '如果你对权限、协议、漏洞、渗透思路和防守体系更敏感，安全路径会更能发挥优势。',
     '7k-17k / 月', '图搜索', '安全工程师', 'security', '高强度',
     '["Web 安全","系统安全","渗透测试","安全审计","漏洞分析"]',
     '["CTF Wiki","OWASP Testing Guide","网络安全工程实践"]',
     '["白帽子讲 Web 安全","Web 安全攻防","网络是怎样连接的"]',
     '["信息安全竞赛","CTF 省赛/国赛","强网杯校园赛"]',
     '["CISP","CompTIA Security+","阿里云安全认证"]',
     '[{"skill":"风险识别","target":88,"description":"要能识别高危面与攻击链条"},{"skill":"漏洞分析","target":84,"description":"需要具备复现、定位与修复建议能力"},{"skill":"安全加固","target":82,"description":"权限、日志和基线配置要形成闭环"}]',
     5, 1),
    (6, 'bigdata', '大数据平台与数据工程', 'Big Data', 'data', '适合喜欢规模化数据处理和平台建设的同学',
     '围绕数据采集、清洗、流批处理、数仓建模和平台稳定性展开，强调规模、链路和数据质量意识。',
     '如果你更喜欢构建稳定的数据链路、处理大规模数据，而不是只做页面或单点模型，数据工程会更适合你。',
     '7k-16k / 月', '队列', '大数据开发', 'bigdata', '高强度',
     '["Spark","Flink","数仓建模","数据管道","分布式系统"]',
     '["Spark 官方文档","Flink 基础训练营","数仓建模课程"]',
     '["Hadoop 权威指南","Spark 快速大数据分析","数据库系统概念"]',
     '["大数据挑战赛","高校数据工程赛","企业数据平台实践赛"]',
     '["Cloudera Data Platform","阿里云大数据 ACP","Databricks Associate"]',
     '[{"skill":"数据链路设计","target":86,"description":"要能从采集到消费设计完整链路"},{"skill":"分布式理解","target":84,"description":"容错、吞吐和一致性要知道边界"},{"skill":"数仓思维","target":80,"description":"建模、指标口径和质量治理决定平台价值"}]',
     6, 1),
    (7, 'analysis', '数据分析与商业洞察', 'Analytics', 'data', '适合喜欢用数据支撑判断的同学',
     '强调统计分析、可视化表达、指标体系和业务解释，要求你不仅会算，还要能把结论讲给别人听懂。',
     '如果你对数据背后的业务含义和结论表达更感兴趣，数据分析路径会比纯工程路径更适合你。',
     '6k-13k / 月', 'Python', '数据分析师', 'analysis', '稳扎稳打',
     '["Python","Pandas","SQL","统计学","可视化"]',
     '["Google Data Analytics","Kaggle Learn","Python 数据分析课程"]',
     '["利用 Python 进行数据分析","深入浅出统计学","数据分析实战"]',
     '["市场调查大赛","数学建模竞赛","商业分析挑战赛"]',
     '["CDA 数据分析师","Google Data Analytics Certificate","Tableau Desktop Specialist"]',
     '[{"skill":"数据清洗","target":86,"description":"口径、缺失值与异常值处理要稳定"},{"skill":"分析建模","target":82,"description":"统计分析和可视化要服务于结论输出"},{"skill":"业务表达","target":84,"description":"要能把图表和指标转成可执行建议"}]',
     7, 1),
    (8, 'product', '产品策划与需求设计', 'Product', 'strategy', '适合喜欢沟通、拆问题和推动落地的同学',
     '围绕需求分析、方案设计、优先级取舍和协作推进展开，强调你能否把模糊问题变成可执行方案。',
     '如果你在团队里经常主动梳理流程、协调分工、明确目标，产品路径很可能适合你。',
     '6k-14k / 月', '逻辑表达', '产品经理', 'product', '稳扎稳打',
     '["需求分析","用户研究","方案设计","项目推进","指标思维"]',
     '["人人都是产品经理","数字产品管理课程","产品方法论训练营"]',
     '["启示录","结网","用户体验要素"]',
     '["互联网创新创业赛","电子商务三创赛","商业分析挑战赛"]',
     '["NPDP","软考系统集成项目管理工程师","Google Project Management"]',
     '[{"skill":"需求拆解","target":88,"description":"要能把模糊需求拆成清晰任务和优先级"},{"skill":"方案表达","target":84,"description":"原型、流程和文档要能让研发快速理解"},{"skill":"推进协作","target":82,"description":"跨角色沟通和节奏把控决定落地效率"}]',
     8, 1),
    (9, 'design', 'UI/UX 设计与体验优化', 'Design', 'experience', '适合喜欢信息层级、视觉表达和体验细节的同学',
     '聚焦视觉规范、交互体验、设计系统和用户研究，强调审美判断力与问题表达能力。',
     '如果你会天然关注版式、层级、按钮反馈和信息负担，设计路径会更容易让你做出成就感。',
     '6k-13k / 月', '交互设计', '交互设计师', 'design', '稳扎稳打',
     '["Figma","交互设计","设计系统","用户研究","信息架构"]',
     '["Figma 官方教程","Google UX Design","设计系统工作坊"]',
     '["写给大家看的设计书","点石成金","用户体验要素"]',
     '["计算机设计大赛数媒组","广告艺术大赛","交互设计作品赛"]',
     '["Adobe Certified Professional","Google UX Design Certificate","腾讯设计力认证"]',
     '[{"skill":"视觉表达","target":86,"description":"字体、色彩、层级和节奏要形成体系"},{"skill":"交互设计","target":84,"description":"流程、反馈和操作成本需要被清晰考虑"},{"skill":"设计协作","target":80,"description":"设计稿、标注和组件规范要支撑研发落地"}]',
     9, 1),
    (10, 'qa', '测试开发与质量保障', 'QA', 'infrastructure', '适合喜欢复现问题和搭质量体系的同学',
     '强调接口验证、自动化测试、性能测试和发布质量保障，适合逻辑细致、稳定性意识强的同学。',
     '如果你经常能快速发现边界问题、异常流程和隐藏风险，测试开发路径会比普通开发更匹配你。',
     '6k-14k / 月', '自动化测试', '测试开发工程师', 'qa', '进阶型',
     '["自动化测试","接口测试","性能测试","质量体系","持续集成"]',
     '["Postman Learning Center","Selenium 官方文档","测试开发训练营"]',
     '["Google 软件测试之道","软件测试的艺术","持续交付"]',
     '["软件测试大赛","自动化测试技能赛","企业质量工程挑战赛"]',
     '["ISTQB Foundation","JMeter 认证","阿里云 DevOps 认证"]',
     '[{"skill":"测试设计","target":86,"description":"要覆盖正常流程、边界值和异常链路"},{"skill":"自动化能力","target":84,"description":"接口、UI 与回归流程要逐步自动化"},{"skill":"质量意识","target":82,"description":"发布前风险评估和问题闭环决定质量上限"}]',
     10, 1),
    (11, 'cloud', '云平台与运维自动化', 'Cloud', 'infrastructure', '适合喜欢系统稳定性、部署和平台效率的同学',
     '聚焦 Linux、容器化、持续交付、监控告警和自动化运维，强调稳定性、可观测和平台化能力。',
     '如果你会天然关注部署、日志、容器、集群和服务稳定性，云平台路径很值得重点投入。',
     '7k-17k / 月', '容器调度', '云平台工程师', 'cloud', '高强度',
     '["Linux","Docker","Kubernetes","监控告警","DevOps"]',
     '["Docker 官方文档","Kubernetes 官方教程","DevOps 实战训练营"]',
     '["Kubernetes 权威指南","UNIX/Linux 系统管理技术手册","凤凰项目"]',
     '["云计算应用大赛","云原生挑战赛","运维自动化实战赛"]',
     '["AWS Cloud Practitioner","阿里云 ACA 云计算","CKA"]',
     '[{"skill":"部署与交付","target":86,"description":"镜像、流水线和发布流程要熟练"},{"skill":"监控与排障","target":84,"description":"日志、指标和告警联动是核心能力"},{"skill":"平台化思维","target":82,"description":"不是只会救火，而是能设计稳定机制"}]',
     11, 1),
    (12, 'game', '游戏开发与实时交互', 'Game', 'experience', '适合喜欢创作、图形表达和实时系统的同学',
     '围绕 Unity、实时交互、图形表现、性能优化和玩法实现展开，要求兼顾创意与工程能力。',
     '如果你更希望做出可直接被用户体验到的作品，同时愿意打磨性能和交互反馈，游戏方向会更适合你。',
     '6k-15k / 月', '实时交互', '游戏客户端开发', 'game', '进阶型',
     '["Unity","图形基础","实时交互","性能优化","游戏玩法实现"]',
     '["Unity Learn","Game Programming Patterns","实时交互项目实战"]',
     '["游戏编程模式","Unity 3D 游戏开发","计算机图形学基础"]',
     '["游戏开发大赛","高校游戏创意赛","实时交互体验赛"]',
     '["Unity Certified User","Unity Associate","Unreal Authorized Instructor Prep"]',
     '[{"skill":"玩法实现","target":86,"description":"逻辑、状态和交互反馈要足够顺手"},{"skill":"实时性能","target":82,"description":"帧率、内存和资源管理是关键"},{"skill":"创意落地","target":80,"description":"从创意到可玩原型需要持续迭代"}]',
     12, 1);

INSERT IGNORE INTO t_growth_track_stage (
    id, track_id, stage_no, phase_code, title, duration, goal, resource_name, resource_url,
    practice_keyword, action_hint, focus_skills_json, sort_order, status
) VALUES
    (101, 1, 1, 'backend-foundation', 'Java 与数据库基础补齐', '2-3 周', '先把 Java、SQL、集合、多线程和缓存基础打稳，避免后端学习一上来就卡在语言和数据库上。', '黑马程序员 Java 零基础', 'https://www.bilibili.com/video/BV12J41137hu', 'Java 基础', '先夯实语言与数据库', '["Java","MySQL","Redis"]', 1, 1),
    (102, 1, 2, 'backend-project', '服务端项目与接口设计', '2-3 周', '用 Spring Boot 做一个完整业务系统，重点训练接口分层、权限、分页和异常处理。', 'Spring Boot 项目实战', 'https://www.bilibili.com/video/BV1LQ4y1J7cM', '接口设计', '做一个完整后端项目', '["Spring Boot","接口设计","权限控制"]', 2, 1),
    (103, 1, 3, 'backend-deliver', '缓存、性能与面试表达', '1-2 周', '补齐 Redis、SQL 优化与高频面试表达，形成可投递状态。', 'Redis 核心原理与实战', 'https://www.bilibili.com/video/BV1cr4y1671t', '哈希', '把项目和高频问答串起来', '["Redis","SQL 调优","系统表达"]', 3, 1),
    (104, 2, 1, 'frontend-foundation', 'Vue 与组件化基础', '1-2 周', '把 Vue 3、响应式、组件通信和常见列表/表单页面练顺。', 'Vue 3 从入门到实战', 'https://www.bilibili.com/video/BV1Zy4y1K7SH', 'Web 逻辑', '先练页面拆分与状态管理', '["Vue 3","组件化","状态管理"]', 1, 1),
    (105, 2, 2, 'frontend-project', 'TypeScript 与复杂交互页面', '2 周', '补类型系统、可维护性和复杂页面组织，避免只会写静态页面。', 'TypeScript 进阶课', 'https://www.bilibili.com/video/BV1Xy4y1v7S2', '字符串', '把页面做成可维护工程', '["TypeScript","复杂交互","工程化"]', 2, 1),
    (106, 2, 3, 'frontend-deliver', '性能优化与作品表达', '1 周', '围绕性能优化、作品展示和面试表达做最后冲刺。', '前端工程化性能优化', 'https://www.bilibili.com/video/BV1Yf4y1w7xE', '二叉树', '准备可展示作品集', '["性能优化","作品表达","组件复用"]', 3, 1),
    (107, 3, 1, 'ai-foundation', '机器学习与数据处理基础', '2-3 周', '先把数据处理、训练流程、评估指标和常见模型思路补齐。', '吴恩达机器学习课程', 'https://www.coursera.org/learn/machine-learning', 'Python', '先建立实验与指标意识', '["机器学习","数据处理","评估指标"]', 1, 1),
    (108, 3, 2, 'ai-project', '模型调用与智能应用封装', '2 周', '把模型能力封装成能交付的产品功能，强调输入输出质量和容错。', 'AI 应用开发实战', 'https://www.bilibili.com/video/BV1Rf4y1n7xR', '动态规划', '做一个可演示的智能应用', '["模型调用","Prompt Engineering","服务封装"]', 2, 1),
    (109, 3, 3, 'ai-deliver', '实验结论与面试表达', '1 周', '训练你如何解释模型效果、数据偏差和方案取舍。', '深度学习项目复盘', 'https://www.bilibili.com/video/BV1WZ4y1z7dP', '图搜索', '把实验结果讲清楚', '["实验复盘","效果解释","方案比较"]', 3, 1),
    (110, 4, 1, 'embedded-foundation', 'C/C++ 与单片机基础', '2-3 周', '先把指针、内存、外设和寄存器操作练扎实。', 'STM32 官方教程', 'https://www.st.com/content/st_com/en/support/learning/stm32-education.html', '数组', '先把底层操作打稳', '["C/C++","STM32","寄存器"]', 1, 1),
    (111, 4, 2, 'embedded-project', '驱动调试与设备通信', '2 周', '训练串口、I2C、SPI 与驱动排错，形成真实的调试经验。', '正点原子 STM32 教程', 'https://www.bilibili.com/video/BV1m4411Z7Uz', '队列', '做一个可演示的硬件项目', '["驱动开发","设备通信","调试"]', 2, 1),
    (112, 4, 3, 'embedded-deliver', '系统约束与面试案例', '1 周', '围绕实时性、功耗和约束条件做项目复盘与面试准备。', '嵌入式 Linux 实战', 'https://www.bilibili.com/video/BV1jV41167AT', '图', '总结真实调试案例', '["实时性","功耗","项目复盘"]', 3, 1),
    (113, 5, 1, 'security-foundation', 'Web 安全与常见漏洞', '2 周', '先把认证授权、注入、XSS、CSRF 和日志审计这些高频点补齐。', 'OWASP Web Security Testing Guide', 'https://owasp.org/www-project-web-security-testing-guide/', '哈希', '建立漏洞与风险意识', '["Web 安全","权限","审计"]', 1, 1),
    (114, 5, 2, 'security-project', '攻防演练与漏洞复现', '2 周', '通过靶场、CTF 和实战案例训练复现、定位与修复建议能力。', 'CTF Wiki', 'https://ctf-wiki.org/', '图搜索', '把漏洞复现和修复串起来', '["漏洞复现","攻防演练","修复建议"]', 2, 1),
    (115, 5, 3, 'security-deliver', '安全方案表达与基线设计', '1 周', '训练如何把风险描述、基线方案和整改优先级讲清楚。', '安全工程实践', 'https://www.bilibili.com/video/BV1ab411h7m9', '栈', '形成安全治理表达能力', '["风险描述","安全基线","优先级"]', 3, 1),
    (116, 6, 1, 'bigdata-foundation', '分布式与数据管道基础', '2-3 周', '先理解批流处理、消息队列、数仓建模和数据链路。', 'Spark 官方文档', 'https://spark.apache.org/docs/latest/', '队列', '先理解大规模数据链路', '["Spark","Flink","数仓"]', 1, 1),
    (117, 6, 2, 'bigdata-project', '数仓建模与平台项目', '2 周', '做一个从采集、清洗到分析的完整数据工程项目。', '数仓建模课程', 'https://www.bilibili.com/video/BV1xW4y1m7jm', '矩阵', '形成完整数据链路意识', '["数仓建模","数据清洗","平台项目"]', 2, 1),
    (118, 6, 3, 'bigdata-deliver', '调度、治理与稳定性表达', '1 周', '训练如何解释数据质量、链路延迟和平台治理方案。', 'Flink 实战训练营', 'https://www.bilibili.com/video/BV1Pv411b7hH', '二分', '关注数据质量和稳定性', '["数据治理","调度","稳定性"]', 3, 1),
    (119, 7, 1, 'analysis-foundation', 'Python、SQL 与统计基础', '1-2 周', '先把数据清洗、统计学概念和常用 SQL 写法补齐。', 'Python for Data Analysis', 'https://wesmckinney.com/book/', 'Python', '先建立分析口径和工具熟练度', '["Python","SQL","统计学"]', 1, 1),
    (120, 7, 2, 'analysis-project', '业务分析与可视化表达', '2 周', '做一个完整的数据分析项目，重点训练结论表达和图表叙事。', 'Google Data Analytics', 'https://www.coursera.org/professional-certificates/google-data-analytics', '数组', '做一份能讲的分析报告', '["可视化","业务分析","结论表达"]', 2, 1),
    (121, 7, 3, 'analysis-deliver', '指标复盘与面试表达', '1 周', '整理分析案例，训练如何说明结论依据、限制和建议。', '数据分析实战案例', 'https://www.bilibili.com/video/BV1zA411H7Fx', '字符串', '把结论与建议讲清楚', '["指标体系","案例复盘","结论建议"]', 3, 1),
    (122, 8, 1, 'product-foundation', '需求分析与产品方法论', '1-2 周', '先建立需求识别、优先级判断和用户视角。', '人人都是产品经理', 'https://www.woshipm.com/', '逻辑表达', '学会拆问题与写方案', '["需求分析","优先级","用户视角"]', 1, 1),
    (123, 8, 2, 'product-project', '原型、流程与协作推进', '2 周', '把需求做成原型和流程文档，并跟研发、设计一起推进落地。', '数字产品管理课程', 'https://www.coursera.org/learn/uva-darden-digital-product-management', '流程设计', '把模糊想法变成执行方案', '["原型设计","流程图","协作推进"]', 2, 1),
    (124, 8, 3, 'product-deliver', '案例复盘与岗位表达', '1 周', '围绕需求取舍、上线复盘和指标变化准备面试故事。', '产品案例拆解课', 'https://www.bilibili.com/video/BV1sK4y1r7gS', '数据解释', '形成产品案例讲述能力', '["案例复盘","指标分析","沟通表达"]', 3, 1),
    (125, 9, 1, 'design-foundation', '视觉与交互基础', '1-2 周', '建立版式、层级、色彩和常见交互模式基础。', 'Figma 官方教程', 'https://help.figma.com/hc/en-us/categories/360002051613', '交互设计', '先打通视觉和交互基础', '["版式","色彩","交互"]', 1, 1),
    (126, 9, 2, 'design-project', '设计系统与体验方案', '2 周', '围绕设计系统、组件规范和完整体验方案做项目练习。', 'Google UX Design', 'https://www.coursera.org/professional-certificates/google-ux-design', '信息架构', '做一套可复用设计规范', '["设计系统","体验方案","组件规范"]', 2, 1),
    (127, 9, 3, 'design-deliver', '作品集与设计表达', '1 周', '整理作品集，训练如何讲设计目标、约束与效果。', '站酷高赞作品拆解', 'https://www.zcool.com.cn/', '表达设计', '输出一套作品集案例', '["作品集","设计表达","效果验证"]', 3, 1),
    (128, 10, 1, 'qa-foundation', '测试基础与用例设计', '1-2 周', '先把等价类、边界值、异常流程和缺陷描述补齐。', '软件测试基础课程', 'https://www.bilibili.com/video/BV1gL411q7eU', '自动化测试', '先学会设计高质量测试点', '["测试设计","边界值","缺陷描述"]', 1, 1),
    (129, 10, 2, 'qa-project', '接口自动化与回归体系', '2 周', '用 Postman、JUnit、Selenium 或 Playwright 形成自动化闭环。', 'Postman Learning Center', 'https://learning.postman.com/', '接口测试', '把手工测试逐步自动化', '["接口测试","UI 自动化","回归体系"]', 2, 1),
    (130, 10, 3, 'qa-deliver', '质量指标与发布保障', '1 周', '围绕发布风险、质量门禁和问题复盘做岗位表达准备。', '持续交付实战', 'https://www.bilibili.com/video/BV1Br4y1A7gS', '异常流程', '训练质量结果的表达能力', '["发布保障","质量指标","问题复盘"]', 3, 1),
    (131, 11, 1, 'cloud-foundation', 'Linux、容器与脚本基础', '2 周', '先把 Linux、Shell、Docker 与常用运维动作练熟。', 'Docker 官方文档', 'https://docs.docker.com/', '容器调度', '把基础部署链路打通', '["Linux","Docker","Shell"]', 1, 1),
    (132, 11, 2, 'cloud-project', 'K8s、监控与发布流程', '2-3 周', '做一套可观测、可发布、可回滚的云原生部署链路。', 'Kubernetes 官方教程', 'https://kubernetes.io/docs/tutorials/', '图搜索', '做一套完整运维流水线', '["Kubernetes","监控告警","发布流程"]', 2, 1),
    (133, 11, 3, 'cloud-deliver', '排障复盘与平台表达', '1 周', '把真实问题的排查、回滚和治理方案讲成可复用案例。', 'DevOps 实战复盘', 'https://www.bilibili.com/video/BV1xT4y1Q7sb', '系统排障', '形成平台化治理表达', '["排障","回滚","平台治理"]', 3, 1),
    (134, 12, 1, 'game-foundation', 'Unity 与实时交互基础', '2 周', '先把 Unity、对象系统、输入响应和常见玩法逻辑练顺。', 'Unity Learn', 'https://learn.unity.com/', '实时交互', '先做出可玩的最小原型', '["Unity","实时交互","玩法逻辑"]', 1, 1),
    (135, 12, 2, 'game-project', '玩法设计与性能优化', '2-3 周', '做一个完整可试玩 Demo，并训练帧率、资源和场景管理。', 'Game Programming Patterns', 'https://gameprogrammingpatterns.com/', '图', '把创意做成能玩的作品', '["玩法设计","性能优化","资源管理"]', 2, 1),
    (136, 12, 3, 'game-deliver', '作品展示与团队协作', '1 周', '整理作品演示、玩法亮点和协作过程，准备投递表达。', '游戏 Demo 复盘课', 'https://www.bilibili.com/video/BV1cV411Y7W4', '状态管理', '准备完整作品展示材料', '["作品展示","协作复盘","效果表达"]', 3, 1);
