CREATE TABLE IF NOT EXISTS `t_growth_track` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL COMMENT '路径编码',
  `name` varchar(100) NOT NULL COMMENT '路径名称',
  `short_name` varchar(64) NOT NULL COMMENT '短名称',
  `category` varchar(64) NOT NULL COMMENT '分类',
  `subtitle` varchar(255) NOT NULL COMMENT '副标题',
  `description` text NOT NULL COMMENT '路径描述',
  `fit_scene` text NOT NULL COMMENT '适配场景',
  `salary_range` varchar(64) DEFAULT NULL COMMENT '薪资区间',
  `recommended_keyword` varchar(128) DEFAULT NULL COMMENT '推荐练题关键词',
  `interview_position` varchar(128) DEFAULT NULL COMMENT '推荐面试岗位',
  `icon_key` varchar(64) DEFAULT NULL COMMENT '图标标识',
  `difficulty_label` varchar(64) DEFAULT NULL COMMENT '难度标签',
  `tags_json` text COMMENT '标签列表',
  `courses_json` text COMMENT '课程列表',
  `books_json` text COMMENT '书籍列表',
  `competitions_json` text COMMENT '竞赛列表',
  `certificates_json` text COMMENT '证书列表',
  `competency_json` text COMMENT '能力模型',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_growth_track_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成长路径';
CREATE TABLE IF NOT EXISTS `t_growth_track_stage` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `track_id` bigint NOT NULL COMMENT '路径ID',
  `stage_no` int NOT NULL COMMENT '阶段编号',
  `phase_code` varchar(64) NOT NULL COMMENT '阶段编码',
  `title` varchar(255) NOT NULL COMMENT '阶段标题',
  `duration` varchar(64) NOT NULL COMMENT '建议时长',
  `goal` text NOT NULL COMMENT '阶段目标',
  `resource_name` varchar(255) DEFAULT NULL COMMENT '资源名称',
  `resource_url` varchar(500) DEFAULT NULL COMMENT '资源链接',
  `practice_keyword` varchar(128) DEFAULT NULL COMMENT '练题关键词',
  `action_hint` varchar(255) DEFAULT NULL COMMENT '阶段动作提示',
  `focus_skills_json` text COMMENT '聚焦技能',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_growth_track_stage` (`track_id`,`sort_order`),
  CONSTRAINT `fk_growth_stage_track` FOREIGN KEY (`track_id`) REFERENCES `t_growth_track` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成长路径阶段';
CREATE TABLE IF NOT EXISTS `t_growth_assessment_question` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `version_no` int NOT NULL COMMENT '版本号',
  `question_no` int NOT NULL COMMENT '题号',
  `dimension` varchar(64) NOT NULL COMMENT '维度',
  `title` varchar(255) NOT NULL COMMENT '题目',
  `description` text COMMENT '题目说明',
  `question_type` varchar(32) NOT NULL DEFAULT 'single_choice' COMMENT '题型',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_growth_assessment_question` (`version_no`,`question_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成长测评题目';
CREATE TABLE IF NOT EXISTS `t_growth_assessment_option` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `question_id` bigint NOT NULL COMMENT '题目ID',
  `option_key` varchar(16) NOT NULL COMMENT '选项标识',
  `option_title` varchar(255) NOT NULL COMMENT '选项标题',
  `option_desc` varchar(500) DEFAULT NULL COMMENT '选项描述',
  `score_json` text NOT NULL COMMENT '各路径分值',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_growth_assessment_option` (`question_id`,`option_key`),
  CONSTRAINT `fk_growth_option_question` FOREIGN KEY (`question_id`) REFERENCES `t_growth_assessment_question` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成长测评选项';
CREATE TABLE IF NOT EXISTS `t_growth_assessment_result` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT '学生ID',
  `assessment_version` int NOT NULL COMMENT '测评版本',
  `answer_json` longtext NOT NULL COMMENT '答题记录',
  `score_json` longtext NOT NULL COMMENT '路径得分',
  `top_track_codes_json` text NOT NULL COMMENT '推荐路径编码',
  `summary` text NOT NULL COMMENT '结果摘要',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_growth_assessment_user` (`user_id`),
  CONSTRAINT `fk_growth_result_user` FOREIGN KEY (`user_id`) REFERENCES `t_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成长测评结果';
